Add systematic blocking
tidymodels/spatialsample pull request #22
Opened 2022-05-26 14:28 UTC by mikemahoney218

This PR adds a systematic method for assigning blocks to folds, numbering blocks in a grid sequentially starting from the bottom-left corner of the grid. If `ordering = "snake"`, the default, this ordering moves left-to-right for the first row of grid cells, right-to-left for the second row of grid cells, and continues the pattern from there. If `ordering = "continuous"`, ordering is left-to-right for each row. If `relevant_only = TRUE`, only blocks containing data are labelled; if `relevant_only = FALSE` all blocks are labeled, potentially resulting in entire folds with no data.

After this, we've implemented 3/3 block assignment methods in [blockCV](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/2041-210X.13107) (one of them via `spatial_clustering_cv()`, by doing eg `spatial_clustering_cv(ames, coords = c(Lot_Area))`) and 3/4 methods in [Roberts et al 2016](https://onlinelibrary.wiley.com/doi/full/10.1111/ecog.02881). 

The missing method from Roberts is an "optimized random" sampling, where folds are specifically assigned to minimize dissimilarity in predictor space. I'd appreciate talking with you all about this -- they mention it as a way to assess interpolation accuracy when a model won't be used to extrapolate, but I'm concerned about supporting that and potentially undermining the "pit of success" we've got here by making it too easy to assess your model on a purposefully easy benchmark.

(ETA: We're agreed that we're not going to move forward on incorporating predictor-space into blocking at the moment)

``` r
library(spatialsample)
library(ggplot2)
data(ames, package = "modeldata")
data(Sacramento, package = "modeldata")

ames_sf <- sf::st_as_sf(ames, coords = c("Longitude", "Latitude"), crs = 4326)

Sacramento_sf <- sf::st_as_sf(Sacramento, coords = c("longitude", "latitude"), crs = 4326)

make_plot <- function(data, title) {
  do.call(
    rbind, 
    lapply(
      seq_len(nrow(data)), 
      \(x) cbind(assessment(data$splits[[x]]), fold = factor(x))
    )
  ) |> 
    ggplot(aes(color = fold)) + 
    geom_sf() + 
    coord_sf(crs = 4326) + 
    theme_minimal() + 
    labs(title = title)
}

set.seed(123)
spatial_block_cv(ames_sf, v = 5, square = FALSE, cellsize = 0.005, method = "systematic") |> 
  make_plot(title = "Ames 5-fold")
```

![](https://i.imgur.com/tu5sWHS.png)

``` r
spatial_block_cv(ames_sf, 
         v = 5, 
         square = FALSE, 
         n = 100, 
         method = "systematic",
         ordering = "continuous",
         relevant_only = FALSE) |> 
  make_plot(title = "Ames 5-fold")
```

![](https://i.imgur.com/58Opmun.png)

``` r
spatial_block_cv(Sacramento_sf, v = 20, method = "systematic") |> 
  make_plot(title = "Sacramento 20-fold")
```

![](https://i.imgur.com/XhKTv5S.png)

<sup>Created on 2022-05-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

2022-05-27 10:26 UTC, hfrick approved these changes
Looks good! I left a suggestion about improving how the error messages are shown to the user, which you could apply to lower-level check functions. If you use that, it'd be good to require rlang minimum version 1.0.0.

2022-05-27 13:10 UTC, mikemahoney218 commented
Seems to be some test failures related to the RStudio CDN. Not sure what to do about that other than to come back later.

2022-05-27 15:52 UTC, mikemahoney218 commented
Looks like the outage is wrapping up -- CI passed at last.

2022-05-31 21:59 UTC, juliasilge requested changes
I think we need either a new approach or more error checking for the arguments:

``` r
library(spatialsample)
data(Smithsonian, package = "modeldata")
smithsonian_sf <- sf::st_as_sf(Smithsonian,
                               coords = c("longitude", "latitude"),
                               # Set CRS to WGS84
                               crs = 4326)
set.seed(123)
spatial_block_cv(smithsonian_sf, v = 3)
#> #  3-fold spatial block cross-validation 
#> # A tibble: 3 × 2
#>   splits         id   
#>   <list>         <chr>
#> 1 <split [3/17]> Fold1
#> 2 <split [18/2]> Fold2
#> 3 <split [19/1]> Fold3
set.seed(123)
spatial_block_cv(smithsonian_sf, v = 3, method = "systematic")
#> #  3-fold spatial block cross-validation 
#> # A tibble: 3 × 2
#>   splits         id   
#>   <list>         <chr>
#> 1 <split [19/1]> Fold1
#> 2 <split [3/17]> Fold2
#> 3 <split [18/2]> Fold3
set.seed(123)
spatial_block_cv(smithsonian_sf, v = 3, method = "systematic", ordering = "continuous")
#> #  3-fold spatial block cross-validation 
#> # A tibble: 3 × 2
#>   splits         id   
#>   <list>         <chr>
#> 1 <split [19/1]> Fold1
#> 2 <split [3/17]> Fold2
#> 3 <split [18/2]> Fold3
set.seed(123)
spatial_block_cv(smithsonian_sf, v = 3, method = "random", ordering = "continuous")
#> #  3-fold spatial block cross-validation 
#> # A tibble: 3 × 2
#>   splits         id   
#>   <list>         <chr>
#> 1 <split [3/17]> Fold1
#> 2 <split [18/2]> Fold2
#> 3 <split [19/1]> Fold3
```

<sup>Created on 2022-05-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

In the last case, the user will get `method = "random"` and passing in `ordering = "continuous"` doesn't do anything but also does not error.

I'm trying to find other examples we have of arguments that only are applied when a previous argument has a certain value. Do you have some good patterns of this you have seen?

One idea is to make an argument like `systematic_opts = list()`. You can document what goes in the list, add an example, check the input (that is it NULL if "random" and the names if "systematic"), and keep `rlang::arg_match()` in the lower level function for checking `ordering = c("snake", "continuous")`. I'm not saying definitely do this, but it is one option for making this more foolproof.

2022-05-31 21:59 UTC, juliasilge commented on R/spatial_block_cv.R
> +        ),
Let's switch over to `glue::glue()` for our error messages in this package, starting here. You can add glue to Imports.

2022-05-31 21:59 UTC, juliasilge commented on R/spatial_block_cv.R
> +  }
Do [we need `drop = FALSE` here](https://adv-r.hadley.nz/subsetting.html#simplify-preserve)?

2022-05-31 21:59 UTC, juliasilge commented on R/spatial_block_cv.R
> +  # to the row numbers that intersect with blocks in the fold
This is so helpful! 🙏

2022-05-31 21:59 UTC, juliasilge commented on R/spatial_clustering_cv.R
>    split_objs <- purrr::map(indices, make_splits,
Make this a new line break (after `map(`) and then reindent this function call.

2022-05-31 21:59 UTC, juliasilge commented on tests/testthat/test-spatial_clustering_cv.R
>      spatial_clustering_cv(Smithsonian,
I'd break the line after `spatial_cluster_cv(` and then reindent

2022-06-01 17:07 UTC, hfrick commented
Awesome! 🎉 Just named the arg, otherwise good to go @juliasilge !

2022-06-01 19:05 UTC, merged